import type { ReactNode } from 'react';
const unavailable = async () => { throw new Error('Authentication is disconnected in Canvas design preview.'); };
const getToken = async () => null;
const auth = { isLoaded: true, isSignedIn: false, userId: null, sessionId: null, sessionClaims: null, getToken, signOut: async () => {} };
const user = { isLoaded: true, isSignedIn: false, user: null };
const clerk = { signOut: auth.signOut, session: null, user: null, openSignIn: unavailable, openUserProfile: unavailable };
export const ClerkProvider = ({ children }: { children: ReactNode }) => children;
export const SignedOut = ClerkProvider;
export const SignedIn = () => null;
export const ClerkLoaded = ClerkProvider;
export const ClerkLoading = () => null;
export const useAuth = () => auth;
export const useUser = () => user;
export const useClerk = () => clerk;
export const useSession = () => ({ isLoaded: true, isSignedIn: false, session: null });
export const useSignIn = () => ({ isLoaded: true, signIn: { status: 'needs_identifier', create: unavailable, password: unavailable, finalize: unavailable, emailCode: { sendCode: unavailable, verifyCode: unavailable } }, setActive: unavailable });
export const useSignUp = () => ({ isLoaded: true, signUp: { create: unavailable }, setActive: unavailable });
export const useSignInWithApple = () => ({ startAppleAuthenticationFlow: unavailable });
export const useSignInWithGoogle = () => ({ startGoogleAuthenticationFlow: unavailable });
export const useSSO = () => ({ startSSOFlow: unavailable });
export const tokenCache = { getToken, saveToken: async () => {}, clearToken: async () => {} };
export const resourceCache = { get: async () => null, set: async () => {}, remove: async () => {} };
